--
-- LAN_WORK  (User) 
--
CREATE USER LAN_WORK
  IDENTIFIED BY PWD_LAN_WORK
  DEFAULT TABLESPACE LAN_WORK_DATA
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 10 Roles for LAN_WORK 
  GRANT CONNECT TO LAN_WORK WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO LAN_WORK WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00000 TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00001 TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00172 TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00175 TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00176 TO LAN_WORK WITH ADMIN OPTION;
  GRANT MATRIXR_00188 TO LAN_WORK WITH ADMIN OPTION;
  GRANT RESOURCE TO LAN_WORK WITH ADMIN OPTION;
  ALTER USER LAN_WORK DEFAULT ROLE ALL;
  -- 7 System Privileges for LAN_WORK 
  GRANT ALTER SYSTEM TO LAN_WORK;
  GRANT CREATE JOB TO LAN_WORK;
  GRANT CREATE PROCEDURE TO LAN_WORK;
  GRANT CREATE SESSION TO LAN_WORK;
  GRANT CREATE TABLE TO LAN_WORK;
  GRANT DEBUG CONNECT SESSION TO LAN_WORK;
  GRANT UNLIMITED TABLESPACE TO LAN_WORK WITH ADMIN OPTION;


